id: AB8ECBACC
title: Aspiration for the Spread of the Guhyagarbha Teachings
type: translation
pechas:
- IA3954999
- I4AC6FF7C
- I25A7C228
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:06:37.695398
  last_modified_at: 2023-01-04 12:06:37.695414
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  IA3954999/7CAA: CC7C
  I4AC6FF7C/96E9: CC7C
  I25A7C228/949E: CC7C
